server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/orderdb
    username: root
    password: Inspiron15
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    refresh:
      bootstrapRegistry:
        enabled: false
  jpa:
    data-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE
  config:
    import: configserver:http://localhost:9296 #this config : import will tell order-service to go this server to fetch the configurations

#Commenting out eureka server details as we are going to get config details from config server
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADRESS:http://localhost:8761/eureka}
